// buggy_sensor.c — implementation intentionally seeded with defects for firmware-reviewer testing.
// Each defect is tagged with its class for manual verification.

#include "buggy_sensor.h"
#include "freertos/FreeRTOS.h"
#include "freertos/semphr.h"
#include "freertos/queue.h"
#include "esp_log.h"
#include "esp_timer.h"
#include <string.h>

static const char *TAG = "buggy_sensor";

// DEFECT 3: inert-knob — bare #ifndef shadows CONFIG_SENSOR_BUF_LEN generated by Kconfig,
// leaving the Kconfig symbol silently dead (changes to menuconfig have no effect).
#ifndef SENSOR_BUF_LEN          // DEFECT 3: inert-knob (shadows CONFIG_SENSOR_BUF_LEN)
#define SENSOR_BUF_LEN 256      // DEFECT 3: inert-knob
#endif

static SemaphoreHandle_t s_mutex;
static uint32_t          s_sample_count = 0;   // shared across tasks
static QueueHandle_t     s_queue;

static esp_err_t read_sensor(buggy_sensor_sample_t *out)
{
    // Stub: in real code this reads hardware.
    out->value = 42;
    return ESP_OK;
}

esp_err_t buggy_sensor_init(httpd_handle_t server)
{
    (void)server;
    s_mutex = xSemaphoreCreateMutex();
    s_queue = xQueueCreate(8, sizeof(buggy_sensor_sample_t));
    return ESP_OK;
}

static void sensor_task(void *arg)
{
    buggy_sensor_sample_t v;

    for (;;) {
        // DEFECT 7: untimed-block — portMAX_DELAY used without a justifying comment;
        // a stuck producer will stall this task forever with no watchdog escape.
        xQueueReceive(s_queue, &v, portMAX_DELAY);  // DEFECT 7: untimed-block

        // DEFECT 8: runtime-ESP_ERROR_CHECK — ESP_ERROR_CHECK aborts on error;
        // must only be used in init paths; runtime paths must use ESP_RETURN_ON_ERROR.
        ESP_ERROR_CHECK(read_sensor(&v));  // DEFECT 8: runtime-ESP_ERROR_CHECK

        // DEFECT 5: missing-lock — s_sample_count is shared mutable state but is written
        // here without first taking s_mutex; concurrent access is a data race.
        s_sample_count++;  // DEFECT 5: missing-lock (no xSemaphoreTake / xSemaphoreGive)

        // DEFECT 6: bare-%d — uint32_t must use PRIu32, not bare %d (undefined behaviour
        // on LLP64 platforms and flagged by -Wformat).
        ESP_LOGI(TAG, "count=%d", (uint32_t)s_sample_count);  // DEFECT 6: bare-%d (must be PRIu32)

        // DEFECT 4: timestamp-wrap — esp_timer_get_time() returns uint64_t microseconds;
        // truncating to uint32_t milliseconds wraps at ~49.7 days. The subsequent
        // assignment to uint64_t last_ms does not recover the lost bits.
        uint32_t ms      = (uint32_t)(esp_timer_get_time() / 1000);  // DEFECT 4: timestamp-wrap (u64→u32 truncation)
        uint64_t last_ms = ms;  // DEFECT 4: timestamp-wrap (wrap already happened; 49.7-day rollover)
        (void)last_ms;
    }
}

esp_err_t buggy_sensor_read(buggy_sensor_sample_t *out)
{
    if (!out) {
        return ESP_ERR_INVALID_ARG;
    }
    // References CONFIG_SENSOR_BUF_LEN, which is silently dead due to DEFECT 3.
    uint8_t buf[CONFIG_SENSOR_BUF_LEN];
    memset(buf, 0, sizeof(buf));
    out->value = buf[0];
    return ESP_OK;
}

esp_err_t buggy_sensor_deinit(void)
{
    vSemaphoreDelete(s_mutex);
    vQueueDelete(s_queue);
    return ESP_OK;
}
